### ISSUE TITLE
使用出错，报js错误

### ISSUE THREAD

**Issue by ap0806109** [poemp/id-swgger-bootsrap-ui#1]
![wx20181108-105203](https://user-images.githubusercontent.com/5742657/48174918-cc51e300-e344-11e8-8f27-ea35800c5eb0.png)

**Comment by poemp** [comment]
你是怎么操作, 我使用的是最新的版本, 
`swagger2Version = "2.9.2"
    swaggerBootstrapVersion = "1.8.7"`


`compile("com.github.xiaoymin:swagger-bootstrap-ui:${swaggerBootstrapVersion}"){
        exclude group:"org.slf4j"
    }

    compile("io.springfox:springfox-swagger2:${swagger2Version}")`

首先我使用的gradle, 如果使用的是maven的话, 可以去公开的maven仓库里面找到最新的版本.

**Comment by poemp** [comment]
您还可以去swagger-ui的github或者是码云上去查看一下
[GitHub:](https://github.com/xiaoymin/Swagger-Bootstrap-UI)
[码云Gitee:](https://gitee.com/xiaoym/swagger-bootstrap-ui)
