### ISSUE TITLE
接口是排序的？

### ISSUE THREAD

**Issue by qq742464260** [poemp/id-swgger-bootsrap-ui#2]
你好，我想请教一下接口文档是按什么排序的？我想按字母排序
![63keg_ h7s_q5hsgs wp_ e](https://user-images.githubusercontent.com/38743425/50629176-754c4100-0f76-11e9-89b4-963f06efaaba.png)

**Comment by poemp** [comment]
嘿, 你好, 内部使用的红黑树, 按照tags标签来的, 所以不会出现按照字典排序, 需要排序的话, 可以使用自定义的编号.
 我使用的是:
`@RestController
@RequestMapping
@Api(value = "测试", tags = {"00-测试"})
public class CommonController {
   
}`
最后的效果是这样的:
![image](https://user-images.githubusercontent.com/15979497/50642809-47cbbb80-0fa7-11e9-8b45-5a8ae196e8a8.png)
希望能够帮到你

**Comment by tanCfan** [comment]
您好，请问同一tag下存在多个子标签的话，子标签能否支持排序？我尝试给子标签添加了序号，但是发现并不奏效。
